package featuresextraction.utilities;

public enum SupportedFeatures {
    /**
     * Dynamic Features
     **/
    NUM_OF_STAGES, EXECUTOR_RUN_TIME, EXECUTOR_CPU_TIME, INPUT_BYTES, INPUT_RECORDS_COUNT, OUTPUT_BYTES,
    OUTPUT_RECORDS_COUNT, SHUFFLE_READ_BYTES, SHUFFLE_READ_RECORDS, SHUFFLE_WRITE_BYTES, SHUFFLE_WRITE_RECORDS,
    MEMORY_BYTES_SPILLED, DISK_BYTES_SPILLED, RDDS_AFFECTED_COUNT , CPU_TIME_RATIO, MEMORY_SPILLING_RATIO,
    DISK_SPILLING_RATIO,

    /**
     * Static Features
     **/
    IS_AGGREGATE, IS_JOIN, IS_PROJECTION
    }
